### ISSUE TITLE
Build new FAP for Firmware v0.95.0?

### ISSUE THREAD

**Issue by AlexLandherr** [nmrr/flipperzero-rfidbeacon#1]
Would it be possible for you to build a new FAP for firmware version v0.95.0?

I tried your FAP today and it wouldn't work.

**Comment by nmrr** [comment]
Hello,

I suggest you to download the extra pack of compiled plugins:
https://github.com/xMasterX/all-the-plugins/releases/tag/3dec2023

Build has been made for the last firmware

**Comment by AlexLandherr** [comment]
Is there a pack like this for the official firmware? I can't find it on the link you provided.

I also don't want to risk my device by running unofficial firmware.

**Comment by nmrr** [comment]
There is no risk to use custom firmware on the dolphin.
I just build for you this app with the last official toolchain : https://www.mediafire.com/file/0fwzkrya582o61i/flipper_rfidbeacon.fap/file

For the next time : 
git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
mv flipper_rfidbeacon ../flipperzero-firmware/applications_user/
./fbt launch_app APPSRC=applications_user/flipper_rfidbeacon

**Comment by AlexLandherr** [comment]
I followed the instructions for installing your FAP for the Unleashed FW and there seems to be some mismatch as the FAP won't start.

Below is my FW info:
![image](https://github.com/nmrr/flipperzero-rfidbeacon/assets/86981389/23314550-6be1-4e6f-ac53-f9c173d7316d)

**Comment by nmrr** [comment]
Can you use my compiled addon ? I used the official toolchain

**Comment by AlexLandherr** [comment]
And keep the Unleashed FW? Or should I reinstall v0.95.0 of the official one?

**Comment by nmrr** [comment]
I'm sure my build works on unleashed, can you try ? API version should be the same on both firmware.

**Comment by AlexLandherr** [comment]
Got this result with the compiled add-on on both Unleashed FW and the official v0.95.0:

![image](https://github.com/nmrr/flipperzero-rfidbeacon/assets/86981389/82300bd6-b3a2-44c1-bd2f-eb57e9746fc1)
