### ISSUE TITLE
LED Output option

### ISSUE THREAD

**Issue by maxamis** [nmrr/flipperzero-rfidbeacon#2]
Cool app ! Have you ever thought of having an option to send the output to an LED attached to maybe Pin 7/C3 (that is the pin the flashlight uses so thought it would be familiar for people to connect LED there and have the morse code be a visible one).

**Comment by nmrr** [comment]
Hello,

It's a good suggestion for the next release. Currently the internal led of the flipper flashes in red during transmitting

**Comment by darrylburke** [comment]
FYI. I tried to run this on the Xtreme firmware but it gives an error about missing imports and fails to run.

**Comment by nmrr** [comment]
Hello,

Have you used the .app file of the repo or have you rebuild the app ? The .fap of the repo is outdated and you have to rebuild the app with the right toolchain to run this app
